# Generated by Django 2.2.5 on 2021-07-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinformation',
            name='desc',
        ),
    ]
