# Generated by Django 2.2.5 on 2021-07-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_bookinformation_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinformation',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
